If the directory for the project does not exist, print a nice error message rather than screens full of errors

diff --git a/bin/create b/bin/create
--- a/bin/create
+++ b/bin/create
@@ -77,6 +77,10 @@ if [ -d "$PROJECT_PATH" ]; then
 		echo "\033[31mError: $PROJECT_PATH is not empty. Please specify an empty folder.\033[m"
 		exit 1
 	fi
+else
+	echo "\033[31mError: $PROJECT_PATH does not exist. Please specify an empty folder.\033[m"
+	exit 1
+
 fi
 
 # copy the files in; then modify them
