[CB-1802] ./cordova set of CLI tools need audit to work with paths with spaces

diff --git a/bin/templates/project/cordova/run b/bin/templates/project/cordova/run
--- a/bin/templates/project/cordova/run
+++ b/bin/templates/project/cordova/run
@@ -20,31 +20,26 @@
 
 set -e
 
-CORDOVA_PATH=$( cd "$( dirname "$0" )" && pwd )
-PROJECT_PATH=$CORDOVA_PATH/..
 
-function getAppPath() {
-	for file in "$( find "$PROJECT_PATH" -type d -name '*.xcodeproj' | sort )"; do
-	  PROJECT_NAME=$(basename "$file" .xcodeproj)
-	done;
-	APP=build/$PROJECT_NAME.app
-	APP_PATH="$PROJECT_PATH/$APP"
-}
+CORDOVA_PATH=$( cd "$( dirname "$0" )" && pwd -P)
+PROJECT_PATH="$(dirname "$CORDOVA_PATH")"
+XCODEPROJ=$( ls "$PROJECT_PATH" | grep .xcodeproj  )
+PROJECT_NAME=$(basename "$XCODEPROJ" .xcodeproj)
 
 APP_PATH=$1
 
 if [ $# -lt 1 ]; then
-	getAppPath
+	APP_PATH="$PROJECT_PATH/build/$PROJECT_NAME.app"
 fi
 
 if [ ! -d "$APP_PATH" ]; then
 	echo "Project '$APP_PATH' is not built. Building."
-  $CORDOVA_PATH/debug || exit $?
+    $CORDOVA_PATH/debug || exit $?
 fi
 
 if [ ! -d "$APP_PATH" ]; then
-		echo "$APP_PATH not found to emulate."
-		exit 1
+	echo "$APP_PATH not found to emulate."
+	exit 1
 fi
 
 # launch using ios-sim
