[CB-2943] Tweak ./cordova/run project-level script for iOS

diff --git a/bin/templates/project/cordova/run b/bin/templates/project/cordova/run
--- a/bin/templates/project/cordova/run
+++ b/bin/templates/project/cordova/run
@@ -1,4 +1,4 @@
-#! /bin/sh
+#!/usr/bin/env bash 
 #
 # Licensed to the Apache Software Foundation (ASF) under one
 # or more contributor license agreements.  See the NOTICE file
@@ -17,8 +17,78 @@
 # specific language governing permissions and limitations
 # under the License.
 #
+# Valid values for "--target" (case insensitive):
+#     "iPhone (Retina 3.5-inch)" (default)
+#     "iPhone (Retina 4-inch)"
+#     "iPhone"
+#     "iPad"
+#     "iPad (Retina)"
 
 set -e
+
+OPTION_RESULT=()
+TARGET="iPhone (Retina 3.5-inch)"
+TARGET_FLAG='--family iphone --retina'
+
+# separates "key=value", sets an array with 0th index as key, 1st index as value
+_parseOption() 
+{
+    local ARG=$@
+    OIFS=$IFS
+    IFS='='
+
+    OPTION_RESULT=()
+    for i in ${ARG[@]}
+    do
+      OPTION_RESULT+=($i)
+    done
+
+    IFS=$OIFS
+}
+
+# parses key=value arguments
+_parseArgs()
+{
+  for arg in "$@"
+  do
+    _parseOption ${arg}
+    case "${OPTION_RESULT[0]}" in
+      "--target")
+        TARGET=${OPTION_RESULT[1]}
+        ;;
+    esac
+  done
+}
+
+_parseArgs "$@"
+
+# "iPhone (Retina 3.5-inch)" -> --family iphone --retina
+# "iPhone (Retina 4-inch)" -> --family iphone --retina --tall
+# "iPhone" -> --family iphone
+# "iPad" -> --family ipad
+# "iPad (Retina)" -> --family ipad --retina
+
+# lowercase the target string
+TARGET_LC=`echo $TARGET | tr '[:upper:]' '[:lower:]'` 
+
+# remember the comparison is lowercase
+case "$TARGET_LC" in
+  "iphone (retina 3.5-inch)")
+    TARGET_FLAG="--family iphone --retina"
+    ;;
+    "iphone (retina 4-inch)")
+    TARGET_FLAG="--family iphone --retina --tall"
+    ;;
+    "iphone")
+    TARGET_FLAG="--family iphone"
+    ;;
+    "ipad")
+    TARGET_FLAG="--family ipad"
+    ;;
+    "ipad (retina)")
+    TARGET_FLAG="--family ipad --retina"
+    ;;
+esac
 
 XCODE_VER=$(xcodebuild -version | head -n 1 | sed -e 's/Xcode //')
 XCODE_MIN_VERSION="4.5"
@@ -33,11 +103,7 @@ PROJECT_PATH="$(dirname "$CORDOVA_PATH")"
 XCODEPROJ=$( ls "$PROJECT_PATH" | grep .xcodeproj  )
 PROJECT_NAME=$(basename "$XCODEPROJ" .xcodeproj)
 
-APP_PATH=$1
-
-if [ $# -lt 1 ]; then
-	APP_PATH="$PROJECT_PATH/build/$PROJECT_NAME.app"
-fi
+APP_PATH="$PROJECT_PATH/build/$PROJECT_NAME.app"
 
 if [ ! -d "$APP_PATH" ]; then
 	echo "Project '$APP_PATH' is not built. Building."
@@ -49,10 +115,19 @@ if [ ! -d "$APP_PATH" ]; then
 	exit 1
 fi
 
-# launch using ios-sim
-if which ios-sim >/dev/null; then
-    ios-sim launch "$APP_PATH" --stderr "$CORDOVA_PATH/console.log" --stdout "$CORDOVA_PATH/console.log" &
-else
-    echo -e '\033[31mError: ios-sim was not found. Please download, build and install version 1.4 or greater from https://github.com/phonegap/ios-sim into your path. Or "brew install ios-sim" using homebrew: http://mxcl.github.com/homebrew/\033[m'; exit 1;
+IOS_SIM_MIN_VERSION="1.5"
+IOS_SIM_LOCATION=$(which ios-sim)
+if [ $? != 0 ]; then
+    echo -e "\033[31mError: ios-sim was not found. Please download, build and install version $IOS_SIM_MIN_VERSION or greater from https://github.com/phonegap/ios-sim into your path. Or 'brew install ios-sim' using homebrew: http://mxcl.github.com/homebrew/\033[m"; exit 1;
+	exit 1
 fi
 
+IOS_SIM_VERSION=$(ios-sim --version)
+
+if [[ "$IOS_SIM_VERSION" < "$IOS_SIM_MIN_VERSION" ]]; then
+	echo "Cordova needs ios-sim version $IOS_SIM_MIN_VERSION or greater, you have version $IOS_SIM_VERSION."
+	exit 1
+fi
+
+# launch using ios-sim
+ios-sim launch "$APP_PATH" --stderr "$CORDOVA_PATH/console.log" --stdout "$CORDOVA_PATH/console.log" $TARGET_FLAG &
